# Generated by Django 4.2.10 on 2025-12-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
    ]
