# Generated by Django 4.2.10 on 2025-12-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('condition', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good')], max_length=20)),
                ('date_collected', models.DateField()),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ewaste_items', to=settings.AUTH_USER_MODEL)),
                ('source_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-date_collected', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='items_ewast_categor_c2b1d7_idx'), models.Index(fields=['date_collected'], name='items_ewast_date_co_fd3fb7_idx'), models.Index(fields=['created_by'], name='items_ewast_created_23c503_idx'), models.Index(fields=['source_supplier'], name='items_ewast_source__b0286d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ewasteitem',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='item_weight_positive'),
        ),
    ]
