# Generated by Django 4.2.10 on 2025-12-25 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer_name', models.CharField(max_length=200)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('stocked', 'Stocked'), ('sold', 'Sold')], default='stocked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ewaste_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='items.ewasteitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ewaste_item'], name='transaction_ewaste__61e880_idx'), models.Index(fields=['date_sold'], name='transaction_date_so_4a9e3f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('sale_price__gte', 0)), name='transaction_sale_price_non_negative'),
        ),
    ]
