# Generated by Django 4.2.10 on 2025-12-27 09:36

from django.db import migrations, models
import django.db.models.deletion


def copy_item_data(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    for transaction in Transaction.objects.select_related('ewaste_item__category'):
        if transaction.ewaste_item_id:
            transaction.category_id = transaction.ewaste_item.category_id
            transaction.weight_kg = transaction.ewaste_item.weight_kg
            transaction.save(update_fields=['category', 'weight_kg'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('items', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_ewaste__61e880_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalog.itemcategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.RunPython(copy_item_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='transaction',
            name='ewaste_item',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='catalog.itemcategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_e3f163_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='transaction_weight_positive'),
        ),
    ]
